import {
  IListContents,
  IWikiDetailContents,
} from "src/interface/interfaceWiki";

export const DWikiList: Array<IListContents> = [
  { title: "코딩 공부 시작하기", id: 1 },
  { title: "HTML/CSS로 웹사이트 만들기", id: 2 },
  { title: "Python 기초", id: 3 },
  { title: "JavaScript 기초", id: 4 },
  { title: "비개발자를 위한 SQL 데이터 분석", id: 5 },
  { title: "React 프론트 개발", id: 6 },
  { title: "Next.js 웹 개발", id: 7 },
  { title: "Node.js 백엔드 개발", id: 8 },
  { title: "컴퓨터 아키텍처", id: 9 },
  { title: "객체지향 프로그래밍", id: 10 },
  { title: "Javascript 프론트 개발자", id: 11 },
  { title: "Javascript 백엔드 개발자", id: 12 },
  { title: "데이터 사이언티스트", id: 13 },
  { title: "딥 러닝", id: 14 },
  { title: "코딩 공부 시작하기", id: 1 },
  { title: "HTML/CSS로 웹사이트 만들기", id: 2 },
  { title: "Python 기초", id: 3 },
  { title: "JavaScript 기초", id: 4 },
  { title: "비개발자를 위한 SQL 데이터 분석", id: 5 },
  { title: "React 프론트 개발", id: 6 },
  { title: "Next.js 웹 개발", id: 7 },
  { title: "Node.js 백엔드 개발", id: 8 },
  { title: "컴퓨터 아키텍처", id: 9 },
  { title: "객체지향 프로그래밍", id: 10 },
  { title: "Javascript 프론트 개발자", id: 11 },
  { title: "Javascript 백엔드 개발자", id: 12 },
  { title: "데이터 사이언티스트", id: 13 },
  { title: "딥 러닝", id: 14 },
];

export const DWikiDetailContents: Array<IWikiDetailContents> = [
  {
    title: "코딩 공부 시작하기",
    id: 1,
    contents:
      "코딩 공부 시작하기 1번 입니다. *HTML/CSS로 웹사이트 만들기* ㅎㅎㅎ",
  },
  {
    title: "HTML/CSS로 웹사이트 만들기",
    id: 2,
    contents: "아설말 *JavaScript 기초* ㅎㅎ",
  },
  { title: "Python 기초", id: 3, contents: "" },
  { title: "JavaScript 기초", id: 4, contents: "" },
  { title: "비개발자를 위한 SQL 데이터 분석", id: 5, contents: "" },
  { title: "React 프론트 개발", id: 6, contents: "" },
  { title: "Next.js 웹 개발", id: 7, contents: "" },
  { title: "Node.js 백엔드 개발", id: 8, contents: "" },
  { title: "컴퓨터 아키텍처", id: 9, contents: "" },
  { title: "객체지향 프로그래밍", id: 10, contents: "" },
  { title: "Javascript 프론트 개발자", id: 11, contents: "" },
  { title: "Javascript 백엔드 개발자", id: 12, contents: "" },
  { title: "데이터 사이언티스트", id: 13, contents: "" },
  { title: "딥 러닝", id: 14, contents: "" },
];
