import { IListContents } from "src/interface/interfaceWiki";

export const DWikiList: Array<IListContents> = [
  { title: "코딩 공부 시작하기", id: 1 },
  { title: "HTML/CSS로 웹사이트 만들기", id: 2 },
  { title: "Python 기초", id: 3 },
  { title: "JavaScript 기초", id: 4 },
  { title: "비개발자를 위한 SQL 데이터 분석", id: 5 },
  { title: "React 프론트 개발", id: 6 },
  { title: "Next.js 웹 개발", id: 7 },
  { title: "Node.js 백엔드 개발", id: 8 },
  { title: "컴퓨터 아키텍처", id: 9 },
  { title: "객체지향 프로그래밍", id: 10 },
  { title: "Javascript 프론트 개발자", id: 11 },
  { title: "Javascript 백엔드 개발자", id: 12 },
  { title: "데이터 사이언티스트", id: 13 },
  { title: "딥 러닝", id: 14 },
  { title: "코딩 공부 시작하기", id: 1 },
  { title: "HTML/CSS로 웹사이트 만들기", id: 2 },
  { title: "Python 기초", id: 3 },
  { title: "JavaScript 기초", id: 4 },
  { title: "비개발자를 위한 SQL 데이터 분석", id: 5 },
  { title: "React 프론트 개발", id: 6 },
  { title: "Next.js 웹 개발", id: 7 },
  { title: "Node.js 백엔드 개발", id: 8 },
  { title: "컴퓨터 아키텍처", id: 9 },
  { title: "객체지향 프로그래밍", id: 10 },
  { title: "Javascript 프론트 개발자", id: 11 },
  { title: "Javascript 백엔드 개발자", id: 12 },
  { title: "데이터 사이언티스트", id: 13 },
  { title: "딥 러닝", id: 14 },
];
